#!/usr/bin/env python3
"""Build a self-contained Kaggle T4 notebook from the lab sources.

    python scripts/build_kaggle.py          # rewrite kaggle/Lab22_DPO_T4.ipynb
    python scripts/build_kaggle.py --check  # fail when the notebook is stale

The Kaggle bundle runs the required path NB0–NB4. It omits bonus-only packages
and creates a small evidence archive in /kaggle/working after NB4 completes.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))

from build_colab import RELEASE_GPU, code, md, percent_cells, requirements  # noqa: E402

WORKDIR = "/kaggle/working/lab22"
TARGET = REPO / "kaggle" / "Lab22_DPO_T4.ipynb"
SCRIPT_TARGET = REPO / "kaggle" / "Lab22_DPO_T4.py"
STAGES = [
    ("00_dpo_loss_from_scratch", "core · CPU"),
    ("01_sft_mini", "core"),
    ("02_preference_data", "core"),
    ("03_dpo_train", "core"),
    ("04_compare_and_eval", "core"),
]
OMIT_REQUIREMENTS = (
    "jupyterlab",
    "jupytext",
    "pytest",
    "llama-cpp-python",
    "lm-eval",
    "openai",
    "anthropic",
)


def kaggle_requirements() -> list[str]:
    return [spec for spec in requirements() if not spec.lower().startswith(OMIT_REQUIREMENTS)]


def package_results_cell() -> str:
    return f'''from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

WORK = Path("{WORKDIR}")
required = [
    "adapters/sft-mini/adapter_config.json",
    "adapters/dpo/adapter_config.json",
    "adapters/dpo/dpo_metrics.json",
    "adapters/dpo/split.json",
    "models/sft-merged/config.json",
    "data/pref/train.parquet",
    "data/pref/eval.parquet",
    "data/pref/stats.json",
    "data/eval/side_by_side.jsonl",
    "data/eval/judge_summary.json",
    "submission/screenshots/02-sft-loss.png",
    "submission/screenshots/02b-pref-length.png",
    "submission/screenshots/03-dpo-reward-curves.png",
    "submission/screenshots/04-side-by-side-table.png",
]
missing = [name for name in required if not (WORK / name).is_file()]
if missing:
    raise FileNotFoundError(f"NB0–NB4 evidence is incomplete: {{missing}}")

optional = sorted((WORK / "data/eval").glob("judge_results_*.json"))
archive_path = Path("/kaggle/working/lab22-results.zip")
with ZipFile(archive_path, "w", compression=ZIP_DEFLATED) as archive:
    for name in required:
        archive.write(WORK / name, arcname=name)
    for path in optional:
        archive.write(path, arcname=path.relative_to(WORK).as_posix())
    archive.writestr(
        "README_RESULTS.md",
        "Unzip these files into the lab repository. The archive contains small evidence files only; "
        "model and adapter weight files are excluded. Copy the real metrics into "
        "submission/REFLECTION.md after reviewing them.\\n",
    )
print(f"Ready to download: {{archive_path}} ({{archive_path.stat().st_size / 1e6:.1f}} MB)")
from IPython.display import FileLink, display
display(FileLink(str(archive_path)))'''


def percent_source(notebook: dict) -> str:
    """Render notebook cells as a Jupytext-compatible Python percent script."""
    lines: list[str] = [
        "# ---",
        "# jupyter:",
        "#   jupytext:",
        "#     formats: ipynb,py:percent",
        "# ---",
        "",
    ]
    for cell in notebook["cells"]:
        source = "".join(cell["source"]).rstrip("\n")
        if cell["cell_type"] == "markdown":
            lines.append("# %% [markdown]")
            lines.extend(("# " + line) if line else "#" for line in source.splitlines())
        else:
            lines.append("# %%")
            lines.extend(source.splitlines())
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render() -> dict:
    pins = " ".join(f'"{spec}"' for spec in kaggle_requirements())
    cells = [
        md(
            "# Lab 22 — DPO/ORPO Alignment (Kaggle T4)\n\n"
            "**Track 3 · Day 22 · VinUni AICB.** Generated by `scripts/build_kaggle.py` from "
            "`notebooks/*.py` and `lab22/*.py`; do not edit by hand.\n\n"
            "Required path: NB0 → NB4. This notebook uses one T4 GPU. Enable Internet so Kaggle can "
            "install the training stack and download the model and datasets. The final cell packages "
            "the small submission evidence files; model weights are excluded."
        ),
        md("## A. Setup\n\nBefore running cells, select a T4 GPU and enable Internet in the Kaggle notebook settings."),
        code(
            'import os\n'
            'os.environ["COMPUTE_TIER"] = "T4"\n'
            '# Optional: reduce memory pressure on a smaller GPU.\n'
            '# os.environ["MAX_LEN"] = "512"\n'
            'print("Tier: T4 (the lab uses GPU 0)")'
        ),
        code(f"!pip install -q {pins}"),
        code(
            "from pathlib import Path\n"
            f'WORK = Path("{WORKDIR}")\n'
            '(WORK / "lab22").mkdir(parents=True, exist_ok=True)\n'
            'os.chdir(WORK)\n'
            'print(Path.cwd())'
        ),
        md("### Helper package `lab22/` (same files as the repository)"),
    ]
    for module in sorted((REPO / "lab22").glob("*.py")):
        body = module.read_text(encoding="utf-8")
        cells.append(code(f"%%writefile {WORKDIR}/lab22/{module.name}\n{body}"))
    for index, (stem, kind) in enumerate(STAGES):
        if index:
            cells.append(code(RELEASE_GPU))
        cells.append(md(f"---\n# ⏵ `notebooks/{stem}.py` ({kind})"))
        cells.extend(percent_cells(REPO / "notebooks" / f"{stem}.py"))
    cells.extend(
        [
            md("---\n# Download the results"),
            md(
                "After NB4 finishes, the next cell creates `/kaggle/working/lab22-results.zip`. "
                "Download it from the notebook output files, then extract it into this repository. "
                "It contains metrics, preference splits, evaluation results, adapter metadata, and "
                "the four required plots; it does not contain model weights or personal credentials."
            ),
            code(package_results_cell()),
        ]
    )
    for index, cell in enumerate(cells):
        # Kaggle's current notebook importer expects the nbformat 4.5 cell id.
        # Keep ids deterministic so --check can compare generated artifacts.
        cell["id"] = f"lab22-{index:03d}"
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the Kaggle notebook is stale")
    args = parser.parse_args()
    notebook = render()
    if args.check:
        stale = []
        if not TARGET.exists() or json.loads(TARGET.read_text(encoding="utf-8")) != notebook:
            stale.append(TARGET.relative_to(REPO))
        if not SCRIPT_TARGET.exists() or SCRIPT_TARGET.read_text(encoding="utf-8") != percent_source(notebook):
            stale.append(SCRIPT_TARGET.relative_to(REPO))
        if stale:
            print(f"stale: {stale}; run `python scripts/build_kaggle.py`")
            return 1
        print(f"current: {TARGET.relative_to(REPO)} and {SCRIPT_TARGET.relative_to(REPO)}")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(json.dumps(notebook, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    SCRIPT_TARGET.write_text(percent_source(notebook), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(REPO)} and {SCRIPT_TARGET.relative_to(REPO)} ({len(notebook['cells'])} cells)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
